# I wrote this while still learning. The "ansible.builtin.package" directive may have been simpler.

- name: "Install MDATP - Debian"
  ansible.builtin.apt:
    name: mdatp
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: "Install MDATP - Red Hat 7"
  ansible.builtin.yum:
    name: mdatp
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '7'

- name: "Install MDATP - Red Hat 8+"
  ansible.builtin.dnf:
    name: mdatp
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version != '7'