- name: "Create MDATP directories"
  ansible.builtin.file:
    path: /etc/opt/microsoft/mdatp/
    recurse: true
    state: directory
    mode: 0755
    owner: root
    group: root

- name: "Register mdatp_onboard.json"
  ansible.builtin.stat:
    path: /etc/opt/microsoft/mdatp/mdatp_onboard.json
  register: mdatp_onboard

- name: "Upload onboarding config"
  ansible.builtin.copy:
    src: mdatp_onboard.json
    dest: /etc/opt/microsoft/mdatp/mdatp_onboard.json
    mode: 0600
    owner: root
    group: root
  when: not mdatp_onboard.stat.exists