- name: Check package updates - RHEL7 (YUM)
  include_tasks: check-yum.yml
  when: ansible_distribution_major_version == '7'

- name: Check package updates - RHEL8+ (DNF)
  include_tasks: check-dnf.yml
  when: ansible_distribution_major_version != '7'