- name: "Change listen address."
  ansible.builtin.replace:
    path: "/var/lib/pgsql/{{ pgsql_version }}/data/postgresql.conf"
    regexp: '\#listen_addresses.*=.*.localhost.'
    replace: "listen_addresses = '0.0.0.0'"
  notify: restart postgresql
  when: open_listen

- name: "Add internal IP range to pg_hba.conf"
  community.postgresql.postgresql_pg_hba:
    dest: "/var/lib/pgsql/{{ pgsql_version }}/data/pg_hba.conf"
    contype: host
    databases: "{{ item.db_name }}"
    users: "{{ item.user }}"
    source: 10.10.0.0/16
    method: scram-sha-256
  loop: "{{ pgsql_roles }}"
  notify: restart postgresql
  when: pgsql_roles is defined
